MASTER_COLUMN_NAMES = ['date',
                       'opp_name',
                       'wl',
                       'score',
                       'opp_score',
                       'fg',
                       'fga',
                       'fgpct',
                       '3p',
                       '3pa',
                       '3ppct',
                       'ft',
                       'fta',
                       'ftpct',
                       'orb',
                       'trb',
                       'ast',
                       'stl',
                       'blk',
                       'tov',
                       'pf',
                       'opp_fg',
                       'opp_fga',
                       'opp_fgpct',
                       'opp_3p',
                       'opp_3pa',
                       'opp_3ppct',
                       'opp_ft',
                       'opp_fta',
                       'opp_ftpct',
                       'opp_orb',
                       'opp_trb',
                       'opp_ast',
                       'opp_stl',
                       'opp_blk',
                       'opp_tov',
                       'opp_pf',
                       'team_name']

MASTER_COLUMN_ORDER = ['date',
                       'team_name'
                       'opp_name',
                       'wl',
                       'score',
                       'opp_score',
                       'fg',
                       'fga',
                       'fgpct',
                       '3p',
                       '3pa',
                       '3ppct',
                       'ft',
                       'fta',
                       'ftpct',
                       'orb',
                       'trb',
                       'ast',
                       'stl',
                       'blk',
                       'tov',
                       'pf',
                       'opp_fg',
                       'opp_fga',
                       'opp_fgpct',
                       'opp_3p',
                       'opp_3pa',
                       'opp_3ppct',
                       'opp_ft',
                       'opp_fta',
                       'opp_ftpct',
                       'opp_orb',
                       'opp_trb',
                       'opp_ast',
                       'opp_stl',
                       'opp_blk',
                       'opp_tov',
                       'opp_pf']

TEAM_NAME_ID_DICT = {'ABILENE CHRISTIAN': 215,
                     'ADAMS STATE': 675,
                     'AIR FORCE': 119,
                     'AKRON': 63,
                     'ALABAMA': 136,
                     'ALABAMA A&AMP;M': 100,
                     'ALABAMA A&M': 420,
                     'ALABAMA STATE': 205,
                     'ALBANY (NY)': 147,
                     'ALBANY STATE (GA)': 542,
                     'ALCORN STATE': 113,
                     'ALICE LLOYD': 714,
                     'AMERICAN': 229,
                     'ANDERSON (SC)': 686,
                     'ANGELO STATE': 587,
                     'ANTELOPE VALLEY': 751,
                     'APPALACHIAN STATE': 326,
                     'AQUINAS': 775,
                     'ARCADIA': 764,
                     'ARIZONA': 31,
                     'ARIZONA STATE': 179,
                     'ARKANSAS': 212,
                     'ARKANSAS BAPTIST': 517,
                     'ARKANSAS STATE': 69,
                     'ARKANSAS-FORT SMITH': 770,
                     'ARKANSAS-PINE BLUFF': 227,
                     'ARLINGTON BAPTIST': 761,
                     'ARMY': 234,
                     'ASBURY': 561,
                     'AUBURN': 171,
                     'AURORA': 550,
                     'AUSTIN PEAY': 353,
                     'AVE MARIA': 385,
                     'AVILA': 400,
                     'BALL STATE': 74,
                     'BARD': 531,
                     'BAYLOR': 122,
                     'BELHAVEN (MS)': 718,
                     'BELLARMINE': 57,
                     'BELLEVUE': 595,
                     'BELMONT': 40,
                     'BENEDICTINE': 478,
                     'BEREA': 652,
                     'BERRY': 520,
                     'BETHANY (WV)': 781,
                     'BETHEL (IN)': 778,
                     'BETHEL (TN)': 759,
                     'BETHESDA UNIVERSITY (CA)': 447,
                     'BETHUNE-COOKMAN': 305,
                     'BINGHAMTON': 137,
                     'BIRMINGHAM-SOUTHERN': 719,
                     'BLACKBURN': 678,
                     'BLOOMSBURG': 757,
                     'BLUE MOUNTAIN COLLEGE': 419,
                     'BOB JONES UNIVERSITY': 642,
                     'BOISE STATE': 236,
                     'BOSTON COLLEGE': 202,
                     'BOSTON UNIVERSITY': 109,
                     'BOWIE STATE': 688,
                     'BOWLING GREEN STATE': 159,
                     'BOYCE': 758,
                     'BRADLEY': 220,
                     'BRESCIA': 399,
                     'BREVARD': 482,
                     'BREWTON-PARKER': 742,
                     'BRIDGEWATER (VA)': 687,
                     'BRIGHAM YOUNG': 3,
                     'BROWN': 293,
                     'BRYAN': 703,
                     'BRYANT': 248,
                     'BRYN ATHYN': 734,
                     'BUCKNELL': 18,
                     'BUFFALO': 46,
                     'BUFFALO STATE': 720,
                     'BUTLER': 213,
                     'BYU': 3,
                     'CAIRN': 571,
                     'CAL POLY': 291,
                     'CAL ST DOMINGUEZ HILLS': 704,
                     'CAL STATE BAKERSFIELD': 53,
                     'CAL STATE FULLERTON': 192,
                     'CAL STATE MARITIME': 731,
                     'CAL STATE NORTHRIDGE': 203,
                     'CAL STATE STANISLAUS': 444,
                     'CALIFORNIA': 277,
                     'CALIFORNIA BAPTIST': 158,
                     'CALUMET COLLEGE': 728,
                     'CAMPBELL': 323,
                     'CAMPBELLSVILLE': 640,
                     'CANISIUS': 143,
                     'CAROLINA': 627,
                     'CARROLL (MT)': 472,
                     'CENTRAL ARKANSAS': 70,
                     'CENTRAL CHRISTIAN': 750,
                     'CENTRAL CONNECTICUT': 438,
                     'CENTRAL CONNECTICUT STATE': 92,
                     'CENTRAL FLORIDA': 83,
                     'CENTRAL MICHIGAN': 88,
                     'CENTRAL PENNSYLVANIA COLLEGE': 649,
                     'CHAMINADE': 626,
                     'CHAMPION CHRISTIAN': 464,
                     'CHARLESTON SOUTHERN': 258,
                     'CHARLOTTE': 76,
                     'CHATTANOOGA': 54,
                     'CHEYNEY': 413,
                     'CHICAGO STATE': 148,
                     'CINCINNATI': 218,
                     'CLARK ATLANTA': 408,
                     'CLARKS SUMMIT': 636,
                     'CLEMSON': 191,
                     'CLEVELAND STATE': 239,
                     'COAST GUARD': 436,
                     'COASTAL CAROLINA': 247,
                     'COASTAL GEORGIA': 423,
                     'COE': 774,
                     'COKER': 743,
                     'COLBY-SAWYER': 780,
                     'COLGATE': 344,
                     'COLLEGE OF CHARLESTON': 329,
                     'COLORADO': 184,
                     'COLORADO CHRISTIAN': 534,
                     'COLORADO COLLEGE': 424,
                     'COLORADO STATE': 297,
                     'COLORADO STATE-PUEBLO': 669,
                     'COLUMBIA': 312,
                     'COLUMBIA INTERNATIONAL': 435,
                     'CONCORDIA (CA)': 596,
                     'CONCORDIA-MOORHEAD': 586,
                     'CONNECTICUT': 144,
                     'COPPIN STATE': 15,
                     'CORNELL': 310,
                     'COVENANT': 372,
                     'CREIGHTON': 188,
                     'CROWN (MN)': 752,
                     'CURRY': 415,
                     "D'YOUVILLE": 528,
                     'DAKOTA WESLEYAN': 452,
                     'DALLAS': 739,
                     'DALLAS CHRISTIAN': 426,
                     'DALTON STATE': 637,
                     'DARTMOUTH': 130,
                     'DAVENPORT': 663,
                     'DAVIDSON': 0,
                     'DAYTON': 320,
                     'DEFIANCE': 373,
                     'DELAWARE': 172,
                     'DELAWARE STATE': 244,
                     'DELAWARE VALLEY': 735,
                     'DELTA STATE': 453,
                     'DENVER': 75,
                     'DEPAUL': 263,
                     'DEPAUW': 591,
                     'DETROIT MERCY': 289,
                     'DILLARD': 567,
                     'DOANE COLLEGE': 593,
                     'DRAKE': 60,
                     'DREXEL': 318,
                     'DUKE': 347,
                     'DUQUESNE': 169,
                     'EAST CAROLINA': 231,
                     'EAST TENNESSEE STATE': 80,
                     'EAST-WEST': 617,
                     'EASTERN ILLINOIS': 111,
                     'EASTERN KENTUCKY': 308,
                     'EASTERN MENNONITE': 599,
                     'EASTERN MICHIGAN': 21,
                     'EASTERN NEW MEXICO': 716,
                     'EASTERN OREGON': 545,
                     'EASTERN WASHINGTON': 33,
                     'ECCLESIA': 568,
                     'EDWARD WATERS': 726,
                     'ELIZABETH CITY STATE': 721,
                     'ELMS': 694,
                     'ELON': 34,
                     'EMERSON': 707,
                     'ERSKINE': 388,
                     'ETSU': 384,
                     'EUREKA': 536,
                     'EVANSVILLE': 128,
                     'EVERGREEN STATE': 547,
                     'FAIRFIELD': 9,
                     'FAIRLEIGH DICKINSON': 287,
                     'FAIRLEIGH DICKINSON-FLORHAM': 732,
                     'FELICIAN': 569,
                     'FERRUM': 379,
                     'FISHER COLLEGE': 367,
                     'FISK': 462,
                     'FLORIDA': 11,
                     'FLORIDA A&AMP;M': 79,
                     'FLORIDA A&M': 79,
                     'FLORIDA ATLANTIC': 163,
                     'FLORIDA GULF COAST': 6,
                     'FLORIDA INTERNATIONAL': 181,
                     'FLORIDA MEMORIAL': 685,
                     'FLORIDA STATE': 354,
                     'FORDHAM': 65,
                     'FORT VALLEY STATE': 697,
                     'FRAMINGHAM STATE': 529,
                     'FRANCISCAN': 604,
                     'FREDONIA STATE': 558,
                     'FRESNO PACIFIC': 386,
                     'FRESNO STATE': 67,
                     'FRIENDS (KS)': 641,
                     'FURMAN': 230,
                     'GALLAUDET': 705,
                     'GARDNER-WEBB': 346,
                     'GEORGE FOX': 733,
                     'GEORGE MASON': 349,
                     'GEORGE WASHINGTON': 209,
                     'GEORGETOWN': 260,
                     'GEORGIA': 185,
                     'GEORGIA SOUTHERN': 193,
                     'GEORGIA STATE': 106,
                     'GEORGIA TECH': 64,
                     'GOLDEY-BEACOM': 378,
                     'GONZAGA': 355,
                     'GOSHEN': 363,
                     'GRAMBLING': 245,
                     'GRAND CANYON': 78,
                     'GREEN BAY': 222,
                     'GREENSBORO': 665,
                     'GWYNEDD-MERCY': 772,
                     'HAMPTON': 256,
                     'HANNIBAL-LAGRANGE': 639,
                     'HARDIN-SIMMONS': 756,
                     'HARRIS-STOWE': 745,
                     'HARTFORD': 754,
                     'HARVARD': 356,
                     'HAWAII': 631,
                     'HAWAII PACIFIC': 692,
                     'HAWAII-HILO': 546,
                     'HEIDELBERG': 513,
                     'HENDRIX': 370,
                     'HIGH POINT': 149,
                     'HOFSTRA': 309,
                     'HOLY CROSS': 55,
                     'HOOD': 515,
                     'HOUSTON': 335,
                     'HOUSTON CHRISTIAN': 241,
                     'HOWARD': 190,
                     'HOWARD PAYNE': 645,
                     'IDAHO': 86,
                     'IDAHO STATE': 224,
                     'ILLINOIS': 223,
                     'ILLINOIS STATE': 105,
                     'ILLINOIS TECH': 589,
                     'ILLINOIS-CHICAGO': 180,
                     'IMMACULATA': 440,
                     'INCARNATE WORD': 103,
                     'INDIANA': 206,
                     'INDIANA STATE': 316,
                     'IONA': 295,
                     'IOWA': 151,
                     'IOWA STATE': 337,
                     'IUPUI': 186,
                     'JACKSON STATE': 317,
                     'JACKSONVILLE': 219,
                     'JACKSONVILLE STATE': 45,
                     'JAMES MADISON': 274,
                     'JARVIS CHRISTIAN': 403,
                     'JOHN BROWN': 364,
                     'JOHN JAY': 430,
                     'JOHNSON & WALES (NC)': 530,
                     'JOHNSON & WALES (RI)': 601,
                     'JOHNSON (FL)': 398,
                     'JOHNSON STATE': 635,
                     'JOHNSON UNIVERSITY': 628,
                     'KANSAS': 253,
                     'KANSAS CHRISTIAN': 434,
                     'KANSAS CITY': 37,
                     'KANSAS STATE': 102,
                     'KEAN': 738,
                     'KEISER': 554,
                     'KENNESAW STATE': 204,
                     'KENT STATE': 154,
                     'KENTUCKY': 269,
                     'KENTUCKY CHRISTIAN': 776,
                     'KENTUCKY STATE': 463,
                     'KENTUCKY WESLEYAN': 479,
                     'KEYSTONE': 521,
                     'KING (TN)': 380,
                     'LA SALLE': 117,
                     'LA SIERRA': 526,
                     'LA VERNE': 368,
                     'LAFAYETTE': 235,
                     'LAGRANGE': 740,
                     'LAKE ERIE': 644,
                     'LAKE SUPERIOR STATE': 537,
                     'LAMAR': 339,
                     'LE MOYNE': 281,
                     'LEHIGH': 56,
                     'LEMOYNE-OWEN': 684,
                     'LETOURNEAU': 572,
                     'LEWIS & CLARK': 432,
                     'LIBERTY': 216,
                     'LIFE': 519,
                     'LIFE PACIFIC': 458,
                     'LIMESTONE': 543,
                     'LINCOLN (MO)': 443,
                     'LINDENWOOD': 95,
                     'LINDSEY WILSON': 746,
                     'LINFIELD': 429,
                     'LIPSCOMB': 254,
                     'LITTLE ROCK': 261,
                     'LIU': 357,
                     'LONG BEACH STATE': 262,
                     'LONG ISLAND UNIVERSITY': 357,
                     'LONGWOOD': 131,
                     'LORAS': 590,
                     'LOUISIANA': 301,
                     'LOUISIANA CHRISTIAN': 706,
                     'LOUISIANA COLLEGE': 564,
                     'LOUISIANA STATE': 62,
                     'LOUISIANA STATE-SHREVEPORT': 727,
                     'LOUISIANA TECH': 29,
                     'LOUISIANA-MONROE': 85,
                     'LOUISVILLE': 259,
                     'LOURDES': 395,
                     'LOYOLA (IL)': 226,
                     'LOYOLA (LA)': 565,
                     'LOYOLA (MD)': 58,
                     'LOYOLA MARYMOUNT': 300,
                     'LSU': 62,
                     'LUTHER': 576,
                     'LYNCHBURG': 673,
                     'LYNDON STATE': 667,
                     'LYNN': 610,
                     'LYON': 566,
                     'MAINE': 175,
                     'MAINE-PRESQUE ISLE': 406,
                     'MALONE': 402,
                     'MANHATTAN': 48,
                     'MARIST': 311,
                     'MARQUETTE': 348,
                     'MARSHALL': 214,
                     'MARY BALDWIN': 691,
                     'MARYLAND': 155,
                     'MARYLAND-BALTIMORE COUNTY': 26,
                     'MARYLAND-EASTERN SHORE': 201,
                     'MARYWOOD': 653,
                     'MASSACHUSETTS': 94,
                     'MASSACHUSETTS-LOWELL': 126,
                     'MAYVILLE STATE': 744,
                     'MCMURRY': 473,
                     'MCNEESE STATE': 120,
                     'MEDGAR EVERS': 722,
                     'MEMPHIS': 296,
                     'MENLO': 609,
                     'MERCER': 282,
                     'MERCHANT MARINE ACADEMY': 650,
                     'MERCY': 737,
                     'MERRIMACK': 194,
                     'MIAMI (FL)': 7,
                     'MIAMI (OH)': 161,
                     'MIAMI-HAMILTON': 646,
                     'MICHIGAN': 164,
                     'MICHIGAN STATE': 35,
                     'MID-AMERICA CHRISTIAN': 428,
                     'MID-ATLANTIC CHRISTIAN': 404,
                     'MIDDLE GEORGIA STATE': 689,
                     'MIDDLE TENNESSEE': 32,
                     'MIDWAY': 414,
                     'MILLIGAN': 575,
                     'MILLSAPS': 417,
                     'MILWAUKEE': 280,
                     'MILWAUKEE ENGINEERING': 690,
                     'MINNESOTA': 124,
                     'MISSISSIPPI': 39,
                     'MISSISSIPPI COLLEGE': 606,
                     'MISSISSIPPI STATE': 51,
                     'MISSISSIPPI UNIVERSITY FOR WOMEN': 708,
                     'MISSISSIPPI VALLEY STATE': 5,
                     'MISSOURI': 135,
                     'MISSOURI BAPTIST UNIVERSITY': 615,
                     'MISSOURI STATE': 264,
                     'MOBILE': 448,
                     'MOLLOY': 477,
                     'MONMOUTH': 265,
                     'MONMOUTH (IL)': 381,
                     'MONTANA': 208,
                     'MONTANA STATE': 351,
                     'MONTANA STATE-NORTHERN': 711,
                     'MONTANA TECH': 712,
                     'MONTEVALLO': 767,
                     'MONTREAT': 768,
                     'MOREHEAD STATE': 84,
                     'MOREHOUSE': 695,
                     'MORGAN STATE': 77,
                     'MOUNT MARTY': 451,
                     'MOUNT OLIVE': 470,
                     'MOUNT SAINT MARY (NY)': 683,
                     'MOUNT SAINT VINCENT': 671,
                     "MOUNT ST. MARY'S": 251,
                     'MT. ST. MARY (NY)': 540,
                     'MURRAY STATE': 96,
                     'MUSKINGUM': 779,
                     'NAVY': 273,
                     'NC STATE': 237,
                     'NEBRASKA': 199,
                     'NEVADA': 24,
                     'NEVADA-LAS VEGAS': 350,
                     'NEW HAMPSHIRE': 328,
                     'NEW MEXICO': 146,
                     'NEW MEXICO STATE': 20,
                     'NEW ORLEANS': 160,
                     'NEWPORT NEWS-APPRENTICE': 583,
                     'NIAGARA': 252,
                     'NICHOLLS STATE': 41,
                     'NJIT': 89,
                     'NORFOLK STATE': 307,
                     'NORTH ALABAMA': 87,
                     'NORTH AMERICAN': 459,
                     'NORTH CAROLINA': 108,
                     'NORTH CAROLINA A&AMP;T': 290,
                     'NORTH CAROLINA A&T': 469,
                     'NORTH CAROLINA CENTRAL': 93,
                     'NORTH CENTRAL (MN)': 618,
                     'NORTH DAKOTA': 17,
                     'NORTH DAKOTA STATE': 82,
                     'NORTH FLORIDA': 278,
                     'NORTH GREENVILLE': 387,
                     'NORTH PARK': 455,
                     'NORTH TEXAS': 302,
                     'NORTH TEXAS AT DALLAS': 389,
                     'NORTHEASTERN': 112,
                     'NORTHERN ARIZONA': 97,
                     'NORTHERN COLORADO': 336,
                     'NORTHERN ILLINOIS': 352,
                     'NORTHERN IOWA': 272,
                     'NORTHERN KENTUCKY': 138,
                     'NORTHERN NEW MEXICO': 483,
                     'NORTHLAND': 612,
                     'NORTHWEST INDIAN COLLEGE': 412,
                     'NORTHWEST NAZARENE': 769,
                     'NORTHWEST UNIVERSITY': 549,
                     'NORTHWESTERN': 165,
                     'NORTHWESTERN STATE': 28,
                     'NORTHWOOD': 680,
                     'NOTRE DAME': 292,
                     'NOTRE DAME (MD)': 600,
                     'OAK HILLS': 725,
                     'OAKLAND': 321,
                     'OAKLAND CITY': 361,
                     'OAKWOOD': 401,
                     'OCCIDENTAL': 624,
                     'OGLETHORPE': 514,
                     'OHIO': 183,
                     'OHIO CHRISTIAN': 643,
                     'OHIO DOMINICAN': 655,
                     'OHIO STATE': 173,
                     'OKLAHOMA': 98,
                     'OKLAHOMA STATE': 270,
                     'OLD DOMINION': 68,
                     'OLE MISS': 39,
                     'OMAHA': 268,
                     'ORAL ROBERTS': 275,
                     'OREGON': 59,
                     'OREGON STATE': 125,
                     'OUR LADY OF THE LAKE': 696,
                     'PACIFIC': 129,
                     'PACIFIC LUTHERAN': 548,
                     'PACIFIC UNION': 602,
                     'PARK (AZ)': 773,
                     'PAUL QUINN': 605,
                     'PENN': 73,
                     'PENN ST. - BRANDYWINE': 541,
                     'PENN ST. - YORK': 570,
                     'PENN ST.-WILKES BARRE': 418,
                     'PENN STATE': 168,
                     'PENN STATE NEW KENSINGTON': 771,
                     'PENN STATE-ALLEGHENY': 676,
                     'PENNSYLVANIA': 73,
                     'PEPPERDINE': 279,
                     'PFEIFFER': 763,
                     'PIEDMONT': 374,
                     'PITT': 176,
                     'PITTSBURGH': 176,
                     'PITTSBURGH-GREENSBURG': 603,
                     'POINT LOMA NAZARENE': 608,
                     'POINT PARK': 441,
                     'PORTLAND': 12,
                     'PORTLAND BIBLE': 681,
                     'PORTLAND STATE': 314,
                     'PRAIRIE VIEW': 333,
                     'PRESBYTERIAN': 1,
                     'PRINCETON': 242,
                     'PROVIDENCE': 47,
                     'PURDUE': 66,
                     'PURDUE FORT WAYNE': 325,
                     'QUEENS (NC)': 4,
                     'QUEENS (NY)': 784,
                     'QUINNIPIAC': 338,
                     'RADFORD': 207,
                     'REGENT': 480,
                     'REINHARDT': 622,
                     'RHODE ISLAND': 152,
                     'RHODE ISLAND COLLEGE': 523,
                     'RICE': 303,
                     'RICHMOND': 115,
                     'RIDER': 283,
                     'RIVIER': 407,
                     'ROBERT MORRIS': 123,
                     'ROCKFORD': 702,
                     'ROCKY MOUNTAIN': 577,
                     'ROSEMONT': 700,
                     'RUST': 723,
                     'RUTGERS': 132,
                     'SACRAMENTO STATE': 162,
                     'SACRED HEART': 118,
                     'SAGINAW VALLEY': 658,
                     'SAGU AMER. INDIAN COLL.': 713,
                     'SAINT FRANCIS (PA)': 267,
                     "SAINT JOSEPH'S": 189,
                     "SAINT JOSEPH'S LONG ISLAND": 461,
                     'SAINT LOUIS': 250,
                     'SAINT MARY (KS)': 553,
                     "SAINT MARY'S": 27,
                     "SAINT MARY'S (CA)": 27,
                     'SAINT MARY-OF-THE-WOODS COLLEGE': 396,
                     "SAINT PETER'S": 22,
                     'SAINT VINCENT (PA)': 736,
                     'SAINT XAVIER (IL)': 783,
                     'SAM HOUSTON': 221,
                     'SAMFORD': 322,
                     'SAN DIEGO': 238,
                     'SAN DIEGO ST.': 294,
                     'SAN DIEGO STATE': 294,
                     'SAN FRANCISCO': 72,
                     'SAN FRANCISCO STATE': 369,
                     'SAN JOSE STATE': 139,
                     'SANTA CLARA': 342,
                     'SARAH LAWRENCE': 442,
                     'SCHREINER': 551,
                     'SCIENCE AND ARTS OF OKLAHOMA': 474,
                     'SEATTLE': 16,
                     'SETON HALL': 319,
                     'SHAWNEE STATE': 578,
                     'SIENA': 174,
                     'SIENA HEIGHTS': 656,
                     'SIU EDWARDSVILLE': 315,
                     'SIU-EDWARDSVILLE': 377,
                     'SMU': 81,
                     'SONOMA STATE': 445,
                     'SOUTH ALABAMA': 334,
                     'SOUTH CAROLINA': 104,
                     'SOUTH CAROLINA STATE': 14,
                     'SOUTH CAROLINA UPSTATE': 195,
                     'SOUTH DAKOTA': 13,
                     'SOUTH DAKOTA MINES': 471,
                     'SOUTH DAKOTA STATE': 177,
                     'SOUTH FLORIDA': 228,
                     'SOUTHEAST MISSOURI STATE': 233,
                     'SOUTHEASTERN LOUISIANA': 345,
                     'SOUTHERN': 330,
                     'SOUTHERN CALIFORNIA': 116,
                     'SOUTHERN ILLINOIS': 49,
                     'SOUTHERN INDIANA': 23,
                     'SOUTHERN METHODIST': 81,
                     'SOUTHERN MISS': 196,
                     'SOUTHERN MISSISSIPPI': 196,
                     'SOUTHERN UTAH': 266,
                     'SOUTHERN VIRGINIA': 527,
                     'SOUTHERN WESLEYAN': 777,
                     'SOUTHERN-NEW ORLEANS': 614,
                     'SOUTHERN–NEW ORLEANS': 765,
                     'SOUTHWEST MINNESOTA STATE': 535,
                     'SOUTHWESTERN ADVENTIST': 466,
                     'SOUTHWESTERN CHRISTIAN': 516,
                     'SOUTHWESTERN OKLAHOMA STATE': 766,
                     'SPALDING': 397,
                     'SPRING HILL': 741,
                     'SPRINGFIELD': 524,
                     'ST. AMBROSE': 638,
                     'ST. ANDREWS': 392,
                     "ST. AUGUSTINE'S": 661,
                     'ST. BONAVENTURE': 36,
                     'ST. ELIZABETH': 662,
                     'ST. FRANCIS (IL)': 390,
                     "ST. JOHN'S (NY)": 200,
                     "ST. JOSEPH'S": 189,
                     "ST. JOSEPH'S–LONG ISLAND": 755,
                     'ST. KATHERINE': 525,
                     "ST. MARY'S (MD)": 562,
                     "ST. PETER'S": 22,
                     'ST. THOMAS': 240,
                     'ST. THOMAS (TX)': 439,
                     'STANFORD': 61,
                     'STEPHEN F. AUSTIN': 90,
                     'STETSON': 271,
                     'STONEHILL': 38,
                     'STONY BROOK': 43,
                     'SUL ROSS STATE': 416,
                     'SUNY DELHI': 532,
                     'SUNY MORRISVILLE': 375,
                     'SUNY-CANTON': 557,
                     'SUNY-MARITIME': 518,
                     'SUNY-ONEONTA': 559,
                     'SUNY-PLATTSBURGH': 634,
                     'SUNY-POTSDAM': 648,
                     'SW ASSEMBL. OF GOD': 456,
                     'SYRACUSE': 107,
                     'TABOR COLLEGE': 699,
                     'TALLADEGA': 710,
                     'TARLETON STATE': 331,
                     'TCU': 286,
                     'TEMPLE': 276,
                     'TENNESSEE': 166,
                     'TENNESSEE STATE': 232,
                     'TENNESSEE TECH': 42,
                     'TENNESSEE WESLEYAN': 666,
                     'TENNESSEE-MARTIN': 332,
                     'TEXAS': 187,
                     'TEXAS A&AMP;M': 145,
                     'TEXAS A&AMP;M-COMMERCE': 304,
                     'TEXAS A&AMP;M-CORPUS CHRISTI': 178,
                     'TEXAS A&M': 145,
                     'TEXAS A&M-COMMERCE': 304,
                     'TEXAS A&M-CORPUS CHRISTI': 178,
                     'TEXAS LUTHERAN': 762,
                     'TEXAS SOUTHERN': 343,
                     'TEXAS STATE': 133,
                     'TEXAS TECH': 313,
                     'TEXAS-RIO GRANDE VALLEY': 10,
                     'TEXAS-TYLER': 630,
                     'THE CITADEL': 141,
                     'THOMAS (ME)': 672,
                     'THOMAS UNIVERSITY': 709,
                     'TIFFIN': 616,
                     'TOCCOA FALLS': 371,
                     'TOLEDO': 243,
                     'TOWSON': 197,
                     'TREVECCA NAZARENE': 698,
                     'TRINITY (FL)': 365,
                     'TRINITY BAPTIST': 460,
                     'TRINITY CHRISTIAN': 475,
                     'TROY': 99,
                     'TRUETT-MCCONNELL': 724,
                     'TRUMAN STATE': 657,
                     'TULANE': 114,
                     'TULSA': 91,
                     'TUSCULUM': 677,
                     'UAB': 340,
                     'UC DAVIS': 19,
                     'UC IRVINE': 170,
                     'UC RIVERSIDE': 134,
                     'UC SAN DIEGO': 284,
                     'UC SANTA BARBARA': 50,
                     'UC-DAVIS': 19,
                     'UC-IRVINE': 170,
                     'UC-MERCED': 468,
                     'UC-RIVERSIDE': 134,
                     'UC-SAN DIEGO': 284,
                     'UCF': 83,
                     'UCLA': 288,
                     'UCONN': 144,
                     'UCSB': 433,
                     'UIC': 180,
                     'UMASS': 94,
                     'UMASS-LOWELL': 126,
                     'UMBC': 26,
                     'UNC': 108,
                     'UNC ASHEVILLE': 225,
                     'UNC GREENSBORO': 358,
                     'UNC WILMINGTON': 257,
                     'UNIV. OF FT. LAUDERDALE': 467,
                     'UNIVERSITY OF THE CUMBERLANDS (KY)': 729,
                     'UNIVERSITY OF THE SOUTHWEST': 580,
                     'UNLV': 350,
                     'USC': 116,
                     'USC UPSTATE': 476,
                     'UT ARLINGTON': 30,
                     'UT-MARTIN': 512,
                     'UTAH': 52,
                     'UTAH STATE': 327,
                     'UTAH TECH': 8,
                     'UTAH VALLEY': 249,
                     'UTEP': 101,
                     'UTSA': 182,
                     'VALLEY CITY STATE': 585,
                     'VALPARAISO': 127,
                     'VANDERBILT': 2,
                     'VANGUARD': 366,
                     'VASSAR': 484,
                     'VCU': 341,
                     'VERMONT': 217,
                     'VILLANOVA': 246,
                     'VIRGINIA': 121,
                     'VIRGINIA COMMONWEALTH': 341,
                     'VIRGINIA TECH': 255,
                     'VIRGINIA WESLEYAN': 427,
                     'VIRGINIA-LYNCHBURG': 421,
                     'VMI': 157,
                     'VOORHEES': 450,
                     'WAGNER': 211,
                     'WAKE FOREST': 324,
                     'WALDORF': 613,
                     'WALLA WALLA': 538,
                     'WARNER PACIFIC': 394,
                     'WARREN WILSON': 539,
                     'WASHINGTON': 25,
                     'WASHINGTON & LEE': 376,
                     'WASHINGTON COLLEGE': 715,
                     'WASHINGTON STATE': 142,
                     'WEBER STATE': 167,
                     'WEST VIRGINIA': 150,
                     'WEST VIRGINIA TECH': 382,
                     'WESTCLIFF': 405,
                     'WESTERN CAROLINA': 620,
                     'WESTERN COLORADO': 633,
                     'WESTERN ILLINOIS': 198,
                     'WESTERN KENTUCKY': 71,
                     'WESTERN MICHIGAN': 153,
                     'WESTERN NEW MEXICO': 579,
                     'WESTERN OREGON': 654,
                     'WESTFIELD STATE': 533,
                     'WESTMINSTER (PA)': 782,
                     'WESTMONT': 625,
                     'WHITTIER': 659,
                     'WICHITA STATE': 110,
                     'WILBERFORCE': 383,
                     'WILEY': 749,
                     'WILKES': 556,
                     'WILLAMETTE': 597,
                     'WILLIAM & MARY': 285,
                     'WILLIAM &AMP; MARY': 285,
                     'WILLIAM CAREY': 457,
                     'WILLIAM JESSUP': 623,
                     'WILLIAM PEACE': 629,
                     'WILLIAM WOODS': 760,
                     'WINTHROP': 210,
                     'WISCONSIN': 306,
                     'WISCONSIN-RIVER FALLS': 753,
                     'WISCONSIN-STOUT': 410,
                     'WITTENBERG': 598,
                     'WOFFORD': 140,
                     'WORCESTER STATE': 409,
                     'WRIGHT STATE': 359,
                     'WYOMING': 298,
                     'XAVIER': 156,
                     'XAVIER (LA)': 360,
                     'YALE': 44,
                     'YORK (NE)': 594,
                     'YOUNGSTOWN STATE': 299}

NON_D1_IDs = {360,
              361,
              363,
              364,
              365,
              366,
              367,
              368,
              369,
              370,
              371,
              372,
              373,
              374,
              375,
              376,
              378,
              379,
              380,
              381,
              382,
              383,
              385,
              386,
              387,
              388,
              389,
              390,
              392,
              394,
              395,
              396,
              397,
              398,
              399,
              400,
              401,
              402,
              403,
              404,
              405,
              406,
              407,
              408,
              409,
              410,
              412,
              413,
              414,
              415,
              416,
              417,
              418,
              419,
              421,
              423,
              424,
              426,
              427,
              428,
              429,
              430,
              432,
              434,
              435,
              436,
              439,
              440,
              441,
              442,
              443,
              444,
              445,
              447,
              448,
              450,
              451,
              452,
              453,
              455,
              456,
              457,
              458,
              459,
              460,
              462,
              463,
              464,
              466,
              467,
              468,
              470,
              471,
              472,
              473,
              474,
              475,
              477,
              478,
              479,
              480,
              482,
              483,
              484,
              513,
              514,
              515,
              516,
              517,
              518,
              519,
              520,
              521,
              523,
              524,
              525,
              526,
              527,
              528,
              529,
              530,
              531,
              532,
              533,
              534,
              535,
              536,
              537,
              538,
              539,
              541,
              542,
              543,
              545,
              546,
              547,
              548,
              549,
              550,
              551,
              553,
              554,
              556,
              557,
              558,
              559,
              561,
              562,
              565,
              566,
              567,
              568,
              569,
              570,
              571,
              572,
              575,
              576,
              577,
              578,
              579,
              580,
              583,
              585,
              586,
              587,
              589,
              590,
              591,
              593,
              594,
              595,
              596,
              597,
              598,
              599,
              600,
              601,
              602,
              603,
              604,
              605,
              606,
              608,
              609,
              610,
              612,
              613,
              615,
              616,
              617,
              618,
              622,
              623,
              624,
              625,
              626,
              627,
              628,
              629,
              630,
              633,
              634,
              635,
              636,
              637,
              638,
              639,
              640,
              641,
              642,
              643,
              644,
              645,
              646,
              648,
              649,
              650,
              652,
              653,
              654,
              655,
              656,
              657,
              658,
              659,
              661,
              662,
              663,
              665,
              666,
              667,
              669,
              671,
              672,
              673,
              675,
              676,
              677,
              678,
              680,
              681,
              683,
              684,
              685,
              686,
              687,
              688,
              689,
              690,
              691,
              692,
              694,
              695,
              696,
              697,
              698,
              699,
              700,
              702,
              703,
              704,
              705,
              706,
              707,
              708,
              709,
              710,
              711,
              712,
              713,
              714,
              715,
              716,
              718,
              719,
              720,
              721,
              722,
              723,
              724,
              725,
              726,
              727,
              728,
              729,
              731,
              732,
              733,
              734,
              735,
              736,
              737,
              738,
              739,
              740,
              741,
              742,
              743,
              744,
              745,
              746,
              749,
              750,
              751,
              752,
              753,
              754,
              755,
              756,
              757,
              758,
              759,
              760,
              761,
              762,
              763,
              764,
              765,
              766,
              767,
              768,
              769,
              770,
              771,
              772,
              773,
              774,
              775,
              776,
              777,
              778,
              779,
              780,
              781,
              782,
              783,
              784}

NON_D1_SCHOOLS = set([name for name, team_id in TEAM_NAME_ID_DICT.items() if team_id in NON_D1_IDs])
