MASTER_COLUMN_NAMES = ['date',
                       'opp_name',
                       'wl',
                       'score',
                       'opp_score',
                       'fg',
                       'fga',
                       'fgpct',
                       '3p',
                       '3pa',
                       '3ppct',
                       'ft',
                       'fta',
                       'ftpct',
                       'orb',
                       'trb',
                       'ast',
                       'stl',
                       'blk',
                       'tov',
                       'pf',
                       'opp_fg',
                       'opp_fga',
                       'opp_fgpct',
                       'opp_3p',
                       'opp_3pa',
                       'opp_3ppct',
                       'opp_ft',
                       'opp_fta',
                       'opp_ftpct',
                       'opp_orb',
                       'opp_trb',
                       'opp_ast',
                       'opp_stl',
                       'opp_blk',
                       'opp_tov',
                       'opp_pf',
                       'team_name']

MASTER_COLUMN_ORDER = ['date',
                       'team_name'
                       'opp_name',
                       'wl',
                       'score',
                       'opp_score',
                       'fg',
                       'fga',
                       'fgpct',
                       '3p',
                       '3pa',
                       '3ppct',
                       'ft',
                       'fta',
                       'ftpct',
                       'orb',
                       'trb',
                       'ast',
                       'stl',
                       'blk',
                       'tov',
                       'pf',
                       'opp_fg',
                       'opp_fga',
                       'opp_fgpct',
                       'opp_3p',
                       'opp_3pa',
                       'opp_3ppct',
                       'opp_ft',
                       'opp_fta',
                       'opp_ftpct',
                       'opp_orb',
                       'opp_trb',
                       'opp_ast',
                       'opp_stl',
                       'opp_blk',
                       'opp_tov',
                       'opp_pf']

TEAM_NAME_ID_DICT = {'ABILENE CHRISTIAN': 215,
                     'AIR FORCE': 119,
                     'AKRON': 63,
                     'ALABAMA': 136,
                     'ALABAMA A&AMP;M': 100,
                     'ALABAMA A&M': 420,
                     'ALABAMA STATE': 205,
                     'ALBANY (NY)': 147,
                     'ALCORN STATE': 113,
                     'AMERICAN': 229,
                     'APPALACHIAN STATE': 326,
                     'ARIZONA': 31,
                     'ARIZONA STATE': 179,
                     'ARKANSAS': 212,
                     'ARKANSAS STATE': 69,
                     'ARKANSAS-PINE BLUFF': 227,
                     'ARMY': 234,
                     'AUBURN': 171,
                     'AUSTIN PEAY': 353,
                     'AVE MARIA': 385,
                     'AVILA': 400,
                     'BALL STATE': 74,
                     'BAYLOR': 122,
                     'BELLARMINE': 57,
                     'BELMONT': 40,
                     'BENEDICTINE': 478,
                     'BETHESDA UNIVERSITY (CA)': 447,
                     'BETHUNE-COOKMAN': 305,
                     'BINGHAMTON': 137,
                     'BLUE MOUNTAIN COLLEGE': 419,
                     'BOISE STATE': 236,
                     'BOSTON COLLEGE': 202,
                     'BOSTON UNIVERSITY': 109,
                     'BOWLING GREEN STATE': 159,
                     'BRADLEY': 220,
                     'BRESCIA': 399,
                     'BREVARD': 482,
                     'BRIGHAM YOUNG': 3,
                     'BROWN': 293,
                     'BRYANT': 248,
                     'BUCKNELL': 18,
                     'BUFFALO': 46,
                     'BUTLER': 213,
                     'BYU': 3,
                     'CAL POLY': 291,
                     'CAL STATE BAKERSFIELD': 53,
                     'CAL STATE FULLERTON': 192,
                     'CAL STATE NORTHRIDGE': 203,
                     'CAL STATE STANISLAUS': 444,
                     'CALIFORNIA': 277,
                     'CALIFORNIA BAPTIST': 158,
                     'CAMPBELL': 323,
                     'CANISIUS': 143,
                     'CARROLL (MT)': 472,
                     'CENTRAL ARKANSAS': 70,
                     'CENTRAL CONNECTICUT': 438,
                     'CENTRAL CONNECTICUT STATE': 92,
                     'CENTRAL FLORIDA': 83,
                     'CENTRAL MICHIGAN': 88,
                     'CHAMPION CHRISTIAN': 464,
                     'CHARLESTON SOUTHERN': 258,
                     'CHARLOTTE': 76,
                     'CHATTANOOGA': 54,
                     'CHEYNEY': 413,
                     'CHICAGO STATE': 148,
                     'CINCINNATI': 218,
                     'CLARK ATLANTA': 408,
                     'CLEMSON': 191,
                     'CLEVELAND STATE': 239,
                     'COAST GUARD': 436,
                     'COASTAL CAROLINA': 247,
                     'COASTAL GEORGIA': 423,
                     'COLGATE': 344,
                     'COLLEGE OF CHARLESTON': 329,
                     'COLORADO': 184,
                     'COLORADO COLLEGE': 424,
                     'COLORADO STATE': 297,
                     'COLUMBIA': 312,
                     'COLUMBIA INTERNATIONAL': 435,
                     'CONNECTICUT': 144,
                     'COPPIN STATE': 15,
                     'CORNELL': 310,
                     'COVENANT': 372,
                     'CREIGHTON': 188,
                     'CURRY': 415,
                     'DAKOTA WESLEYAN': 452,
                     'DALLAS CHRISTIAN': 426,
                     'DARTMOUTH': 130,
                     'DAVIDSON': 0,
                     'DAYTON': 320,
                     'DEFIANCE': 373,
                     'DELAWARE': 172,
                     'DELAWARE STATE': 244,
                     'DELTA STATE': 453,
                     'DENVER': 75,
                     'DEPAUL': 263,
                     'DETROIT MERCY': 289,
                     'DRAKE': 60,
                     'DREXEL': 318,
                     'DUKE': 347,
                     'DUQUESNE': 169,
                     'EAST CAROLINA': 231,
                     'EAST TENNESSEE STATE': 80,
                     'EASTERN ILLINOIS': 111,
                     'EASTERN KENTUCKY': 308,
                     'EASTERN MICHIGAN': 21,
                     'EASTERN WASHINGTON': 33,
                     'ELON': 34,
                     'ERSKINE': 388,
                     'ETSU': 384,
                     'EVANSVILLE': 128,
                     'FAIRFIELD': 9,
                     'FAIRLEIGH DICKINSON': 287,
                     'FERRUM': 379,
                     'FISHER COLLEGE': 367,
                     'FISK': 462,
                     'FLORIDA': 11,
                     'FLORIDA A&AMP;M': 79,
                     'FLORIDA A&M': 79,
                     'FLORIDA ATLANTIC': 163,
                     'FLORIDA GULF COAST': 6,
                     'FLORIDA INTERNATIONAL': 181,
                     'FLORIDA STATE': 354,
                     'FORDHAM': 65,
                     'FRESNO PACIFIC': 386,
                     'FRESNO STATE': 67,
                     'FURMAN': 230,
                     'GARDNER-WEBB': 346,
                     'GEORGE MASON': 349,
                     'GEORGE WASHINGTON': 209,
                     'GEORGETOWN': 260,
                     'GEORGIA': 185,
                     'GEORGIA SOUTHERN': 193,
                     'GEORGIA STATE': 106,
                     'GEORGIA TECH': 64,
                     'GOLDEY-BEACOM': 378,
                     'GONZAGA': 355,
                     'GOSHEN': 363,
                     'GRAMBLING': 245,
                     'GRAND CANYON': 78,
                     'GREEN BAY': 222,
                     'HAMPTON': 256,
                     'HARVARD': 356,
                     'HENDRIX': 370,
                     'HIGH POINT': 149,
                     'HOFSTRA': 309,
                     'HOLY CROSS': 55,
                     'HOUSTON': 335,
                     'HOUSTON CHRISTIAN': 241,
                     'HOWARD': 190,
                     'IDAHO': 86,
                     'IDAHO STATE': 224,
                     'ILLINOIS': 223,
                     'ILLINOIS STATE': 105,
                     'ILLINOIS-CHICAGO': 180,
                     'IMMACULATA': 440,
                     'INCARNATE WORD': 103,
                     'INDIANA': 206,
                     'INDIANA STATE': 316,
                     'IONA': 295,
                     'IOWA': 151,
                     'IOWA STATE': 337,
                     'IUPUI': 186,
                     'JACKSON STATE': 317,
                     'JACKSONVILLE': 219,
                     'JACKSONVILLE STATE': 45,
                     'JAMES MADISON': 274,
                     'JARVIS CHRISTIAN': 403,
                     'JOHN BROWN': 364,
                     'JOHN JAY': 430,
                     'JOHNSON (FL)': 398,
                     'KANSAS': 253,
                     'KANSAS CHRISTIAN': 434,
                     'KANSAS CITY': 37,
                     'KANSAS STATE': 102,
                     'KENNESAW STATE': 204,
                     'KENT STATE': 154,
                     'KENTUCKY': 269,
                     'KENTUCKY STATE': 463,
                     'KENTUCKY WESLEYAN': 479,
                     'KING (TN)': 380,
                     'LA SALLE': 117,
                     'LA VERNE': 368,
                     'LAFAYETTE': 235,
                     'LAMAR': 339,
                     'LE MOYNE': 281,
                     'LEHIGH': 56,
                     'LEWIS & CLARK': 432,
                     'LIBERTY': 216,
                     'LIFE PACIFIC': 458,
                     'LINCOLN (MO)': 443,
                     'LINDENWOOD': 95,
                     'LINFIELD': 429,
                     'LIPSCOMB': 254,
                     'LITTLE ROCK': 261,
                     'LIU': 357,
                     'LONG BEACH STATE': 262,
                     'LONG ISLAND UNIVERSITY': 357,
                     'LONGWOOD': 131,
                     'LOUISIANA': 301,
                     'LOUISIANA STATE': 62,
                     'LOUISIANA TECH': 29,
                     'LOUISIANA-MONROE': 85,
                     'LOUISVILLE': 259,
                     'LOURDES': 395,
                     'LOYOLA (IL)': 226,
                     'LOYOLA (MD)': 58,
                     'LOYOLA MARYMOUNT': 300,
                     'LSU': 62,
                     'MAINE': 175,
                     'MAINE-PRESQUE ISLE': 406,
                     'MALONE': 402,
                     'MANHATTAN': 48,
                     'MARIST': 311,
                     'MARQUETTE': 348,
                     'MARSHALL': 214,
                     'MARYLAND': 155,
                     'MARYLAND-BALTIMORE COUNTY': 26,
                     'MARYLAND-EASTERN SHORE': 201,
                     'MASSACHUSETTS': 94,
                     'MASSACHUSETTS-LOWELL': 126,
                     'MCMURRY': 473,
                     'MCNEESE STATE': 120,
                     'MEMPHIS': 296,
                     'MERCER': 282,
                     'MERRIMACK': 194,
                     'MIAMI (FL)': 7,
                     'MIAMI (OH)': 161,
                     'MICHIGAN': 164,
                     'MICHIGAN STATE': 35,
                     'MID-AMERICA CHRISTIAN': 428,
                     'MID-ATLANTIC CHRISTIAN': 404,
                     'MIDDLE TENNESSEE': 32,
                     'MIDWAY': 414,
                     'MILLSAPS': 417,
                     'MILWAUKEE': 280,
                     'MINNESOTA': 124,
                     'MISSISSIPPI': 39,
                     'MISSISSIPPI STATE': 51,
                     'MISSISSIPPI VALLEY STATE': 5,
                     'MISSOURI': 135,
                     'MISSOURI STATE': 264,
                     'MOBILE': 448,
                     'MOLLOY': 477,
                     'MONMOUTH': 265,
                     'MONMOUTH (IL)': 381,
                     'MONTANA': 208,
                     'MONTANA STATE': 351,
                     'MOREHEAD STATE': 84,
                     'MORGAN STATE': 77,
                     'MOUNT MARTY': 451,
                     'MOUNT OLIVE': 470,
                     "MOUNT ST. MARY'S": 251,
                     'MURRAY STATE': 96,
                     'NAVY': 273,
                     'NC STATE': 237,
                     'NEBRASKA': 199,
                     'NEVADA': 24,
                     'NEVADA-LAS VEGAS': 350,
                     'NEW HAMPSHIRE': 328,
                     'NEW MEXICO': 146,
                     'NEW MEXICO STATE': 20,
                     'NEW ORLEANS': 160,
                     'NIAGARA': 252,
                     'NICHOLLS STATE': 41,
                     'NJIT': 89,
                     'NORFOLK STATE': 307,
                     'NORTH ALABAMA': 87,
                     'NORTH AMERICAN': 459,
                     'NORTH CAROLINA': 108,
                     'NORTH CAROLINA A&AMP;T': 290,
                     'NORTH CAROLINA A&T': 469,
                     'NORTH CAROLINA CENTRAL': 93,
                     'NORTH DAKOTA': 17,
                     'NORTH DAKOTA STATE': 82,
                     'NORTH FLORIDA': 278,
                     'NORTH GREENVILLE': 387,
                     'NORTH PARK': 455,
                     'NORTH TEXAS': 302,
                     'NORTH TEXAS AT DALLAS': 389,
                     'NORTHEASTERN': 112,
                     'NORTHERN ARIZONA': 97,
                     'NORTHERN COLORADO': 336,
                     'NORTHERN ILLINOIS': 352,
                     'NORTHERN IOWA': 272,
                     'NORTHERN KENTUCKY': 138,
                     'NORTHERN NEW MEXICO': 483,
                     'NORTHWEST INDIAN COLLEGE': 412,
                     'NORTHWESTERN': 165,
                     'NORTHWESTERN STATE': 28,
                     'NOTRE DAME': 292,
                     'OAKLAND': 321,
                     'OAKLAND CITY': 361,
                     'OAKWOOD': 401,
                     'OHIO': 183,
                     'OHIO STATE': 173,
                     'OKLAHOMA': 98,
                     'OKLAHOMA STATE': 270,
                     'OLD DOMINION': 68,
                     'OLE MISS': 39,
                     'OMAHA': 268,
                     'ORAL ROBERTS': 275,
                     'OREGON': 59,
                     'OREGON STATE': 125,
                     'PACIFIC': 129,
                     'PENN': 73,
                     'PENN ST.-WILKES BARRE': 418,
                     'PENN STATE': 168,
                     'PENNSYLVANIA': 73,
                     'PEPPERDINE': 279,
                     'PIEDMONT': 374,
                     'PITT': 176,
                     'PITTSBURGH': 176,
                     'POINT PARK': 441,
                     'PORTLAND': 12,
                     'PORTLAND STATE': 314,
                     'PRAIRIE VIEW': 333,
                     'PRESBYTERIAN': 1,
                     'PRINCETON': 242,
                     'PROVIDENCE': 47,
                     'PURDUE': 66,
                     'PURDUE FORT WAYNE': 325,
                     'QUEENS (NC)': 4,
                     'QUINNIPIAC': 338,
                     'RADFORD': 207,
                     'REGENT': 480,
                     'RHODE ISLAND': 152,
                     'RICE': 303,
                     'RICHMOND': 115,
                     'RIDER': 283,
                     'RIVIER': 407,
                     'ROBERT MORRIS': 123,
                     'RUTGERS': 132,
                     'SACRAMENTO STATE': 162,
                     'SACRED HEART': 118,
                     'SAINT FRANCIS (PA)': 267,
                     "SAINT JOSEPH'S": 189,
                     "SAINT JOSEPH'S LONG ISLAND": 461,
                     'SAINT LOUIS': 250,
                     "SAINT MARY'S": 27,
                     "SAINT MARY'S (CA)": 27,
                     'SAINT MARY-OF-THE-WOODS COLLEGE': 396,
                     "SAINT PETER'S": 22,
                     'SAM HOUSTON': 221,
                     'SAMFORD': 322,
                     'SAN DIEGO': 238,
                     'SAN DIEGO ST.': 294,
                     'SAN DIEGO STATE': 294,
                     'SAN FRANCISCO': 72,
                     'SAN FRANCISCO STATE': 369,
                     'SAN JOSE STATE': 139,
                     'SANTA CLARA': 342,
                     'SARAH LAWRENCE': 442,
                     'SCIENCE AND ARTS OF OKLAHOMA': 474,
                     'SEATTLE': 16,
                     'SETON HALL': 319,
                     'SIENA': 174,
                     'SIU EDWARDSVILLE': 315,
                     'SIU-EDWARDSVILLE': 377,
                     'SMU': 81,
                     'SONOMA STATE': 445,
                     'SOUTH ALABAMA': 334,
                     'SOUTH CAROLINA': 104,
                     'SOUTH CAROLINA STATE': 14,
                     'SOUTH CAROLINA UPSTATE': 195,
                     'SOUTH DAKOTA': 13,
                     'SOUTH DAKOTA MINES': 471,
                     'SOUTH DAKOTA STATE': 177,
                     'SOUTH FLORIDA': 228,
                     'SOUTHEAST MISSOURI STATE': 233,
                     'SOUTHEASTERN LOUISIANA': 345,
                     'SOUTHERN': 330,
                     'SOUTHERN CALIFORNIA': 116,
                     'SOUTHERN ILLINOIS': 49,
                     'SOUTHERN INDIANA': 23,
                     'SOUTHERN METHODIST': 81,
                     'SOUTHERN MISS': 196,
                     'SOUTHERN MISSISSIPPI': 196,
                     'SOUTHERN UTAH': 266,
                     'SOUTHWESTERN ADVENTIST': 466,
                     'SPALDING': 397,
                     'ST. ANDREWS': 392,
                     'ST. BONAVENTURE': 36,
                     'ST. FRANCIS (IL)': 390,
                     "ST. JOHN'S (NY)": 200,
                     "ST. JOSEPH'S": 189,
                     "ST. PETER'S": 22,
                     'ST. THOMAS': 240,
                     'ST. THOMAS (TX)': 439,
                     'STANFORD': 61,
                     'STEPHEN F. AUSTIN': 90,
                     'STETSON': 271,
                     'STONEHILL': 38,
                     'STONY BROOK': 43,
                     'SUL ROSS STATE': 416,
                     'SUNY MORRISVILLE': 375,
                     'SW ASSEMBL. OF GOD': 456,
                     'SYRACUSE': 107,
                     'TARLETON STATE': 331,
                     'TCU': 286,
                     'TEMPLE': 276,
                     'TENNESSEE': 166,
                     'TENNESSEE STATE': 232,
                     'TENNESSEE TECH': 42,
                     'TENNESSEE-MARTIN': 332,
                     'TEXAS': 187,
                     'TEXAS A&AMP;M': 145,
                     'TEXAS A&AMP;M-COMMERCE': 304,
                     'TEXAS A&AMP;M-CORPUS CHRISTI': 178,
                     'TEXAS A&M': 145,
                     'TEXAS A&M-COMMERCE': 304,
                     'TEXAS SOUTHERN': 343,
                     'TEXAS STATE': 133,
                     'TEXAS TECH': 313,
                     'TEXAS-RIO GRANDE VALLEY': 10,
                     'THE CITADEL': 141,
                     'TOCCOA FALLS': 371,
                     'TOLEDO': 243,
                     'TOWSON': 197,
                     'TRINITY (FL)': 365,
                     'TRINITY BAPTIST': 460,
                     'TRINITY CHRISTIAN': 475,
                     'TROY': 99,
                     'TULANE': 114,
                     'TULSA': 91,
                     'UAB': 340,
                     'UC DAVIS': 19,
                     'UC IRVINE': 170,
                     'UC RIVERSIDE': 134,
                     'UC SAN DIEGO': 284,
                     'UC SANTA BARBARA': 50,
                     'UC-DAVIS': 19,
                     'UC-IRVINE': 170,
                     'UC-MERCED': 468,
                     'UC-RIVERSIDE': 134,
                     'UC-SAN DIEGO': 284,
                     'UCF': 83,
                     'UCLA': 288,
                     'UCONN': 144,
                     'UCSB': 433,
                     'UIC': 180,
                     'UMASS': 94,
                     'UMASS-LOWELL': 126,
                     'UMBC': 26,
                     'UNC': 108,
                     'UNC ASHEVILLE': 225,
                     'UNC GREENSBORO': 358,
                     'UNC WILMINGTON': 257,
                     'UNIV. OF FT. LAUDERDALE': 467,
                     'UNLV': 350,
                     'USC': 116,
                     'USC UPSTATE': 476,
                     'UT ARLINGTON': 30,
                     'UTAH': 52,
                     'UTAH STATE': 327,
                     'UTAH TECH': 8,
                     'UTAH VALLEY': 249,
                     'UTEP': 101,
                     'UTSA': 182,
                     'VALPARAISO': 127,
                     'VANDERBILT': 2,
                     'VANGUARD': 366,
                     'VASSAR': 484,
                     'VCU': 341,
                     'VERMONT': 217,
                     'VILLANOVA': 246,
                     'VIRGINIA': 121,
                     'VIRGINIA COMMONWEALTH': 341,
                     'VIRGINIA TECH': 255,
                     'VIRGINIA WESLEYAN': 427,
                     'VIRGINIA-LYNCHBURG': 421,
                     'VMI': 157,
                     'VOORHEES': 450,
                     'WAGNER': 211,
                     'WAKE FOREST': 324,
                     'WARNER PACIFIC': 394,
                     'WASHINGTON': 25,
                     'WASHINGTON & LEE': 376,
                     'WASHINGTON STATE': 142,
                     'WEBER STATE': 167,
                     'WEST VIRGINIA': 150,
                     'WEST VIRGINIA TECH': 382,
                     'WESTCLIFF': 405,
                     'WESTERN ILLINOIS': 198,
                     'WESTERN KENTUCKY': 71,
                     'WESTERN MICHIGAN': 153,
                     'WICHITA STATE': 110,
                     'WILBERFORCE': 383,
                     'WILLIAM & MARY': 285,
                     'WILLIAM &AMP; MARY': 285,
                     'WILLIAM CAREY': 457,
                     'WINTHROP': 210,
                     'WISCONSIN': 306,
                     'WISCONSIN-STOUT': 410,
                     'WOFFORD': 140,
                     'WORCESTER STATE': 409,
                     'WRIGHT STATE': 359,
                     'WYOMING': 298,
                     'XAVIER': 156,
                     'XAVIER (LA)': 360,
                     'YALE': 44,
                     'YOUNGSTOWN STATE': 299}

DIVISION_2_IDS = {}
